<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Admin extends MY_Controller {
 public function __construct(){ parent::__construct(); $this->require_login(); $this->load->model(array('Usuario_model','Grupo_model','Resolucion_model')); }
 public function dashboard(){ $this->render('admin/dashboard',array('title'=>'Panel principal')); }
 public function usuarios(){ $this->require_admin(); $this->render('admin/usuarios/index',array('title'=>'Usuarios','usuarios'=>$this->Usuario_model->todos())); }
 public function usuario_crear(){ $this->require_admin();
  if($this->input->method()==='post'){ $this->form_validation->set_rules('nombres','Nombres','required|max_length[150]'); $this->form_validation->set_rules('documento','Documento','required|max_length[30]|is_unique[usuarios.documento]'); $this->form_validation->set_rules('email','Correo','required|valid_email|is_unique[usuarios.email]'); $this->form_validation->set_rules('clave','Clave','required|min_length[8]');
   if($this->form_validation->run()){ $this->Usuario_model->crear(array('nombres'=>$this->input->post('nombres',TRUE),'documento'=>$this->input->post('documento',TRUE),'email'=>$this->input->post('email',TRUE),'clave'=>$this->input->post('clave'),'es_admin'=>$this->input->post('es_admin')?1:0,'activo'=>1)); $this->session->set_flashdata('success','Usuario creado.'); redirect('admin/usuarios'); }}
  $this->render('admin/usuarios/form',array('title'=>'Crear usuario'));
 }
 public function grupos(){ $this->render('admin/grupos/index',array('title'=>'Grupos de resoluciones','grupos'=>$this->Grupo_model->todos())); }
 public function grupo_crear(){ if($this->input->method()==='post'){ $this->form_validation->set_rules('descripcion','Descripción','required|max_length[255]'); if($this->form_validation->run()){ $this->Grupo_model->crear($this->input->post('descripcion',TRUE)); $this->session->set_flashdata('success','Grupo creado.'); redirect('admin/grupos'); }} $this->render('admin/grupos/form',array('title'=>'Crear grupo')); }
 public function resoluciones(){ $this->render('admin/resoluciones/index',array('title'=>'Administrar resoluciones','resoluciones'=>$this->Resolucion_model->todas_admin())); }
 public function enlaces(){
  $this->require_admin(); $novedades=array(); $registros=$this->Resolucion_model->enlaces_a_verificar();
  foreach($registros as $r){ $resultado=$this->verificar_enlace($r); if($resultado['problema']) $novedades[]=array('resolucion'=>$r,'resultado'=>$resultado); }
  $this->render('admin/enlaces',array('title'=>'Novedades de enlaces','novedades'=>$novedades,'total'=>count($registros)));
 }
 private function verificar_enlace($r){
  if($r->archivo){ $ruta=FCPATH.ltrim(str_replace('/',DIRECTORY_SEPARATOR,$r->archivo),DIRECTORY_SEPARATOR); if(!is_file($ruta)) return array('problema'=>true,'tipo'=>'Archivo local','estado'=>'No encontrado','detalle'=>$r->archivo); return array('problema'=>false,'tipo'=>'Archivo local','estado'=>'OK','detalle'=>'Archivo disponible'); }
  if(!$r->url) return array('problema'=>true,'tipo'=>'Sin origen','estado'=>'Sin enlace','detalle'=>'Debe cargar un PDF o registrar una URL.');
  if(!function_exists('curl_init')) return array('problema'=>true,'tipo'=>'URL','estado'=>'No verificable','detalle'=>'La extensión cURL de PHP no está disponible.');
  $ch=curl_init($r->url); curl_setopt_array($ch,array(CURLOPT_NOBODY=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>5,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12,CURLOPT_RETURNTRANSFER=>true,CURLOPT_USERAGENT=>'Corponor Resoluciones Link Checker/1.0',CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2)); curl_exec($ch); $code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE); $error=curl_error($ch); curl_close($ch);
  if($code>=200 && $code<400) return array('problema'=>false,'tipo'=>'URL','estado'=>'HTTP '.$code,'detalle'=>'Enlace disponible'); return array('problema'=>true,'tipo'=>'URL','estado'=>$code?'HTTP '.$code:'Error de conexión','detalle'=>$error?:'El servidor no respondió correctamente.');
 }
 private function upload($field,$dir,$types,$max=10240){ if(empty($_FILES[$field]['name'])) return NULL; $config=array('upload_path'=>FCPATH.$dir,'allowed_types'=>$types,'max_size'=>$max,'encrypt_name'=>TRUE,'remove_spaces'=>TRUE); $this->load->library('upload'); $this->upload->initialize($config); if(!$this->upload->do_upload($field)) throw new RuntimeException(strip_tags($this->upload->display_errors())); return $dir.'/'.$this->upload->data('file_name'); }
 public function resolucion_crear(){ $grupos=$this->Grupo_model->todos(); if($this->input->method()==='post'){ $this->validar_resolucion(); if($this->form_validation->run()){ try { $archivo=$this->upload('archivo','uploads/resoluciones','pdf'); $imagen=$this->upload('imagen','uploads/imagenes','jpg|jpeg|png|webp',4096); if(!$archivo && !$this->input->post('url')) throw new RuntimeException('Debe cargar un archivo PDF o indicar una URL.'); $this->Resolucion_model->crear(array('grupo_id'=>(int)$this->input->post('grupo_id'),'titulo'=>$this->input->post('titulo',TRUE),'fecha_resolucion'=>$this->input->post('fecha_resolucion',TRUE),'archivo'=>$archivo,'url'=>$this->input->post('url',TRUE) ?: NULL,'imagen'=>$imagen,'activo'=>1)); $this->session->set_flashdata('success','Resolución creada.'); redirect('admin/resoluciones'); } catch(Exception $e){ $data['error']=$e->getMessage(); } }} $this->render('admin/resoluciones/form',array_merge($data??array(),array('title'=>'Crear resolución','grupos'=>$grupos,'resolucion'=>NULL))); }
 public function resolucion_editar($id){ $r=$this->Resolucion_model->una((int)$id); if(!$r) show_404(); $grupos=$this->Grupo_model->todos(); if($this->input->method()==='post'){ $this->validar_resolucion(); if($this->form_validation->run()){ try { $archivo=$this->upload('archivo','uploads/resoluciones','pdf'); $imagen=$this->upload('imagen','uploads/imagenes','jpg|jpeg|png|webp',4096); $d=array('grupo_id'=>(int)$this->input->post('grupo_id'),'titulo'=>$this->input->post('titulo',TRUE),'fecha_resolucion'=>$this->input->post('fecha_resolucion',TRUE),'url'=>$this->input->post('url',TRUE) ?: NULL,'activo'=>$this->input->post('activo')?1:0); if($archivo) $d['archivo']=$archivo; if($imagen) $d['imagen']=$imagen; if(!$archivo && !$r->archivo && !$d['url']) throw new RuntimeException('Debe existir archivo PDF o URL.'); $this->Resolucion_model->actualizar($r->id,$d); $this->session->set_flashdata('success','Resolución actualizada.'); redirect('admin/resoluciones'); }catch(Exception $e){$data['error']=$e->getMessage();}}} $this->render('admin/resoluciones/form',array_merge($data??array(),array('title'=>'Editar resolución','grupos'=>$grupos,'resolucion'=>$r))); }
 private function validar_resolucion(){ $this->form_validation->set_rules('grupo_id','Grupo','required|integer'); $this->form_validation->set_rules('titulo','Título','required|max_length[255]'); $this->form_validation->set_rules('fecha_resolucion','Fecha','required|regex_match[/^\d{4}-\d{2}-\d{2}$/]'); if($this->input->post('url')) $this->form_validation->set_rules('url','URL','valid_url|max_length[1000]'); }
}
